// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {HonkVerifier} from "../src/HonkVerifier.sol";
import {HajjSolvencyRegistry} from "../src/HajjSolvencyRegistry.sol";

/// Exercises the registry with REAL UltraHONK proofs generated by packages/prover
/// (contracts/test/fixtures/*.json), verified by the generated HonkVerifier.
contract HajjSolvencyRegistryTest is Test {
    HonkVerifier verifier;
    HajjSolvencyRegistry registry;

    address admin = makeAddr("admin");
    address regulator = makeAddr("regulator");
    address bpkh = makeAddr("bpkh");
    address stranger = makeAddr("stranger");

    uint256 constant PERIOD = 202701;

    function setUp() public {
        verifier = new HonkVerifier();
        registry = new HajjSolvencyRegistry(address(verifier), admin, regulator, bpkh);
    }

    // ---------------------------------------------------------------- helpers

    function _load(string memory state) internal view returns (bytes memory proof, bytes32[] memory inputs) {
        string memory json = vm.readFile(string.concat("test/fixtures/", state, ".json"));
        proof = vm.parseJsonBytes(json, ".proof");
        inputs = vm.parseJsonBytes32Array(json, ".publicInputs");
    }

    uint256 constant PARAM_COUNT = 36;

    // NB: no external calls in here, so it is safe to use between vm.prank and the pranked call.
    function _params(bytes32[] memory inputs) internal pure returns (bytes32[] memory p) {
        p = new bytes32[](PARAM_COUNT);
        for (uint256 i = 0; i < p.length; i++) p[i] = inputs[i];
    }

    function _pin(bytes32[] memory inputs) internal {
        bytes32[] memory p = _params(inputs);
        vm.prank(regulator);
        registry.pinPeriod(p);
    }

    // ---------------------------------------------------------------- happy path

    function test_submit_real_proof_records_result_bits() public {
        (bytes memory proof, bytes32[] memory inputs) = _load("strained");
        _pin(inputs);

        vm.prank(bpkh);
        registry.submitProof(proof, inputs);

        assertTrue(registry.hasRecord(PERIOD));
        HajjSolvencyRegistry.Record memory r = registry.getRecord(PERIOD);
        assertTrue(r.pass[0], "baseline");
        assertTrue(r.pass[1], "moderate");
        assertFalse(r.pass[2], "acute");
        assertEq(r.submitter, bpkh);
        assertEq(registry.submittedCount(), 1);
        assertEq(registry.submittedPeriods()[0], PERIOD);
    }

    function test_all_three_fund_states_verify_with_expected_bits() public {
        string[3] memory states = ["healthy", "strained", "deteriorating"];
        bool[3][3] memory want = [[true, true, true], [true, true, false], [true, false, false]];
        for (uint256 s = 0; s < 3; s++) {
            HajjSolvencyRegistry fresh = new HajjSolvencyRegistry(address(verifier), admin, regulator, bpkh);
            (bytes memory proof, bytes32[] memory inputs) = _load(states[s]);
            bytes32[] memory p = _params(inputs);
            vm.prank(regulator);
            fresh.pinPeriod(p);
            vm.prank(bpkh);
            fresh.submitProof(proof, inputs);
            HajjSolvencyRegistry.Record memory r = fresh.getRecord(PERIOD);
            for (uint256 i = 0; i < 3; i++) assertEq(r.pass[i], want[s][i], states[s]);
        }
    }

    function test_anyone_can_reverify_without_state_change() public {
        (bytes memory proof, bytes32[] memory inputs) = _load("healthy");
        _pin(inputs);
        vm.prank(stranger);
        assertTrue(registry.verifyProof(proof, inputs));
        assertFalse(registry.hasRecord(PERIOD));
    }

    function test_event_emitted() public {
        (bytes memory proof, bytes32[] memory inputs) = _load("deteriorating");
        _pin(inputs);
        vm.expectEmit(true, false, false, false, address(registry));
        emit HajjSolvencyRegistry.SolvencyVerified(PERIOD, true, false, false, bytes32(0), bytes32(0), bpkh);
        vm.prank(bpkh);
        registry.submitProof(proof, inputs);
    }

    // ---------------------------------------------------------------- access control

    function test_only_regulator_can_pin() public {
        (, bytes32[] memory inputs) = _load("healthy");
        bytes32[] memory p = _params(inputs);
        vm.prank(bpkh);
        vm.expectRevert();
        registry.pinPeriod(p);
        vm.prank(stranger);
        vm.expectRevert();
        registry.pinPeriod(p);
    }

    function test_only_prover_can_submit() public {
        (bytes memory proof, bytes32[] memory inputs) = _load("healthy");
        _pin(inputs);
        vm.prank(stranger);
        vm.expectRevert();
        registry.submitProof(proof, inputs);
        vm.prank(regulator);
        vm.expectRevert();
        registry.submitProof(proof, inputs);
    }

    function test_period_cannot_be_repinned() public {
        (, bytes32[] memory inputs) = _load("healthy");
        _pin(inputs);
        bytes32[] memory p = _params(inputs);
        vm.prank(regulator);
        vm.expectRevert(abi.encodeWithSelector(HajjSolvencyRegistry.PeriodAlreadyPinned.selector, PERIOD));
        registry.pinPeriod(p);
    }

    function test_pin_requires_exact_param_count() public {
        bytes32[] memory p = new bytes32[](10);
        vm.prank(regulator);
        vm.expectRevert(abi.encodeWithSelector(HajjSolvencyRegistry.BadParamCount.selector, 10));
        registry.pinPeriod(p);
    }

    // ---------------------------------------------------------------- soundness at the registry

    function test_reject_unpinned_period() public {
        (bytes memory proof, bytes32[] memory inputs) = _load("healthy");
        vm.prank(bpkh);
        vm.expectRevert(abi.encodeWithSelector(HajjSolvencyRegistry.PeriodNotPinned.selector, PERIOD));
        registry.submitProof(proof, inputs);
    }

    function test_reject_easier_stress_parameters() public {
        // The prover proves a softer Acute scenario (0 haircuts) than the regulator pinned.
        (bytes memory proof, bytes32[] memory inputs) = _load("healthy");
        _pin(inputs);
        bytes32[] memory forged = inputs;
        for (uint256 i = 29; i < 35; i++) forged[i] = bytes32(0); // haircut_bps[2][*]
        vm.prank(bpkh);
        vm.expectRevert(abi.encodeWithSelector(HajjSolvencyRegistry.ParamsMismatch.selector, PERIOD));
        registry.submitProof(proof, forged);
    }

    function test_reject_different_attestor_key() public {
        (bytes memory proof, bytes32[] memory inputs) = _load("healthy");
        _pin(inputs);
        bytes32[] memory forged = inputs;
        forged[35] = bytes32(uint256(inputs[35]) ^ 1);
        vm.prank(bpkh);
        vm.expectRevert(abi.encodeWithSelector(HajjSolvencyRegistry.ParamsMismatch.selector, PERIOD));
        registry.submitProof(proof, forged);
    }

    function test_reject_flipped_result_bit() public {
        (bytes memory proof, bytes32[] memory inputs) = _load("deteriorating");
        _pin(inputs);
        bytes32[] memory forged = inputs;
        forged[37] = bytes32(uint256(1)); // claim Moderate passes
        vm.prank(bpkh);
        vm.expectRevert(); // UltraHONK verifier rejects (sumcheck / consistency failure)
        registry.submitProof(proof, forged);
    }

    function test_reject_non_boolean_result() public {
        (bytes memory proof, bytes32[] memory inputs) = _load("healthy");
        _pin(inputs);
        bytes32[] memory forged = inputs;
        forged[36] = bytes32(uint256(2));
        vm.prank(bpkh);
        vm.expectRevert(abi.encodeWithSelector(HajjSolvencyRegistry.NonBooleanResult.selector, 0));
        registry.submitProof(proof, forged);
    }

    function test_reject_tampered_proof_bytes() public {
        (bytes memory proof, bytes32[] memory inputs) = _load("healthy");
        _pin(inputs);
        proof[300] = bytes1(uint8(proof[300]) ^ 0x01);
        vm.prank(bpkh);
        vm.expectRevert();
        registry.submitProof(proof, inputs);
        assertFalse(registry.hasRecord(PERIOD));
    }

    function test_reject_wrong_public_input_count() public {
        (bytes memory proof, bytes32[] memory inputs) = _load("healthy");
        _pin(inputs);
        bytes32[] memory short = new bytes32[](inputs.length - 1);
        for (uint256 i = 0; i < short.length; i++) short[i] = inputs[i];
        vm.prank(bpkh);
        vm.expectRevert(abi.encodeWithSelector(HajjSolvencyRegistry.WrongPublicInputCount.selector, short.length));
        registry.submitProof(proof, short);
    }

    function test_one_proof_per_period_and_replay_blocked() public {
        (bytes memory proof, bytes32[] memory inputs) = _load("healthy");
        _pin(inputs);
        vm.startPrank(bpkh);
        registry.submitProof(proof, inputs);
        vm.expectRevert(abi.encodeWithSelector(HajjSolvencyRegistry.PeriodAlreadySubmitted.selector, PERIOD));
        registry.submitProof(proof, inputs);
        vm.stopPrank();
    }

    function test_statement_replay_across_periods_blocked() public {
        // A statement id already recorded cannot be reused even under a fresh proof/period.
        (bytes memory proof, bytes32[] memory inputs) = _load("strained");
        _pin(inputs);
        vm.prank(bpkh);
        registry.submitProof(proof, inputs);
        assertTrue(registry.statementUsed(inputs[39]));
        assertTrue(registry.proofUsed(keccak256(proof)));
    }

    function test_getRecord_reverts_when_empty() public {
        vm.expectRevert(abi.encodeWithSelector(HajjSolvencyRegistry.NoRecord.selector, PERIOD));
        registry.getRecord(PERIOD);
    }

    // ---------------------------------------------------------------- notary, not custodian

    function test_registry_holds_no_funds() public {
        (bool ok,) = address(registry).call{value: 1 ether}("");
        assertFalse(ok, "registry must not accept ether");
    }

    function test_gas_submit() public {
        (bytes memory proof, bytes32[] memory inputs) = _load("healthy");
        _pin(inputs);
        vm.prank(bpkh);
        uint256 g = gasleft();
        registry.submitProof(proof, inputs);
        emit log_named_uint("submitProof gas", g - gasleft());
    }
}
