/**
 * Writes the Solidity UltraHONK verifier and verification key for the committed
 * circuit artifact to contracts/src/HonkVerifier.sol and circuits/.../target/vk_evm.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { destroyBarretenberg } from '../encoding.js';
import { CONTRACTS_DIR, VK_PATH } from '../paths.js';
import { SolvencyProver } from '../prover.js';

const prover = new SolvencyProver();
const vk = await prover.verificationKey();
writeFileSync(VK_PATH, vk);
const sol = (await prover.solidityVerifier()).replace(
  /^\/\/ SPDX-License-Identifier:.*\n/,
  `// SPDX-License-Identifier: Apache-2.0\n// AUTO-GENERATED by packages/prover (pnpm --filter @hajj-zk/prover export-verifier). Do not edit.\n// Circuit: hajj_solvency, noir ${prover.program.noir_version}, bb.js UltraHonk target=evm.\n`,
);
const out = join(CONTRACTS_DIR, 'src/HonkVerifier.sol');
writeFileSync(out, sol);
console.log(`vk ${vk.length} bytes -> ${VK_PATH}\nverifier ${sol.length} chars -> ${out}`);
await destroyBarretenberg();
